services:
  db:
    image: postgres:15
    container_name: nba_db
    environment:
      - POSTGRES_DB=nba_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ocin3205
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nba_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: nba_backend
    depends_on:
      db:
        condition: service_healthy
        
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/nba_data
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ocin3205
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure

volumes:
  postgres_data: